In [1]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Flatten, Dense, Dropout

print("TensorFlow version :", tf.__version__)

TensorFlow version : 2.16.1


In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = Sequential()
model.add(Flatten(input_shape=(28, 28)))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10))

c:\Users\pangy\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.79306877, -0.20863156, -0.17157423, -0.4394734 ,  0.58191395,
        -0.33465162,  0.5471691 ,  0.9139659 ,  0.2024016 , -0.58041745]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.1697495 , 0.06234127, 0.06469481, 0.04949054, 0.13743748,
        0.05495987, 0.13274424, 0.19156381, 0.09403402, 0.04298441]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.9011517

In [8]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.8599 - loss: 0.4842
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9559 - loss: 0.1512
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9666 - loss: 0.1096
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9726 - loss: 0.0891
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9768 - loss: 0.0732


In [10]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - 878us/step - accuracy: 0.9772 - loss: 0.0723


[0.07234086841344833, 0.9771999716758728]

In [11]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.2724200e-07, 4.3167820e-08, 3.0219687e-06, 4.7765064e-04,
        1.6330647e-08, 3.4491859e-06, 6.5320774e-12, 9.9950731e-01,
        3.6194797e-06, 4.2402330e-06],
       [3.6581426e-07, 4.8647162e-06, 9.9994767e-01, 4.2489624e-05,
        4.2288316e-16, 5.0963382e-07, 2.6566956e-06, 1.4314762e-12,
        1.4719374e-06, 3.5650461e-14],
       [5.7074891e-07, 9.9744129e-01, 1.0919284e-04, 1.1072444e-05,
        8.1589722e-05, 5.5249529e-06, 1.2214915e-04, 2.0135276e-03,
        2.1492830e-04, 2.3833390e-07],
       [9.9886936e-01, 2.0009605e-09, 2.3382272e-05, 1.9842164e-06,
        6.5137306e-06, 2.0040778e-05, 9.6558407e-04, 9.7018361e-05,
        2.5197460e-07, 1.5848449e-05],
       [1.6618645e-07, 1.0150778e-10, 3.1886128e-07, 6.2751786e-09,
        9.9819118e-01, 5.7959067e-08, 1.2249575e-06, 5.0697177e-05,
        8.5224301e-08, 1.7562468e-03]], dtype=float32)>

In [13]:
model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[ -4.031548  ,  -6.707785  ,  -2.4592164 ,   2.6037548 ,
         -7.6798363 ,  -2.3269858 , -15.50391   ,  10.249893  ,
         -2.278794  ,  -2.120506  ],
       [ -0.6375306 ,   1.9501079 ,  14.1835575 ,   4.1173596 ,
        -21.215828  ,  -0.30596328,   1.3451825 , -13.088705  ,
          0.7546792 , -16.781404  ],
       [ -7.355909  ,   7.017845  ,  -2.101988  ,  -4.3906446 ,
         -2.3934007 ,  -5.085829  ,  -1.9898608 ,   0.81254005,
         -1.4247988 ,  -8.229186  ],
       [  8.522743  , -11.505763  ,  -2.1396582 ,  -4.606412  ,
         -3.417724  ,  -2.2938669 ,   1.5810971 ,  -0.7167356 ,
         -6.6700625 ,  -2.5285645 ],
       [ -5.1869254 , -12.587657  ,  -4.5352798 ,  -8.463433  ,
         10.421419  ,  -6.240299  ,  -3.1893744 ,   0.533589  ,
         -5.8547487 ,   4.0786533 ]], dtype=float32)>